### ISSUE TITLE
Strange overlapping of UI components and title bar

### ISSUE THREAD

**Issue by Qix-** [pmsaue0/play#1]
Minor UI blemish; The 'shadow' of the menu button overlaps the taskbar's buttons.

Neat app, I love it already.

<img width="156" alt="screen shot 2017-05-24 at 12 57 22 pm" src="https://cloud.githubusercontent.com/assets/885648/26422966/a2600116-4080-11e7-954c-70d39372956a.png">

**Comment by pmsaue0** [comment]
Thanks for the UI callout, and I'm glad you're enjoying the app :)

I'm addressing the bug you identified in the latest release 2.0.4

I thought I'd try blowing up that hover circle, and try that for a while, it's different, but pretty fun:
<img width="270" alt="large hover circle" src="https://cloud.githubusercontent.com/assets/13648/26425590/32926f90-408a-11e7-9dd6-1c79daf520b9.png">

I'm reluctant to add more padding to fix the header overlap problem, as I'd like to keep the layout frame nice and tight.

Thanks!

**Comment by Qix-** [comment]
> I'm reluctant to add more padding to fix the header overlap problem, as I'd like to keep the layout frame nice and tight.

Completely agree - looks much better. Thanks! :)
